version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    networks:
      - ai_network

  fastapi-gateway:
    build: ./fastapi
    container_name: fastapi-gateway
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - ollama
    networks:
      - ai_network

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    ports:
      - "3000:8080"
    volumes:
      # Montamos un config.json persistente con la URL correcta de Ollama
      #- ./openwebui_config/config.json:/app/backend/data/config.json
      - ./openwebui_config:/app/backend/data
    depends_on:
      - ollama
    networks:
      - ai_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  ai_network:
    driver: bridge
